### ISSUE TITLE
Project Setup

### ISSUE THREAD

**Issue by Irenalou3** [SchoolOfCode/bootcamp-17-bc17-w5-d4_hackathon-rest-api-postgres-hackathon_sql-postgres-node-express#1]
```[tasklist]
### Tasks
- [x] clone the repo
- [x] install project dependencies
- [x] create .env file
- [x] create a database using render
- [x] create schema for database
```
