### ISSUE TITLE
Create

### ISSUE THREAD

**Issue by Irenalou3** [SchoolOfCode/bootcamp-17-bc17-w5-d4_hackathon-rest-api-postgres-hackathon_sql-postgres-node-express#2]
```[tasklist]
### Tasks
- [ ] Discuss and plan the schema
- [ ] Create ERD
- [ ] Change the reset-database.js to match the newly created schema
- [ ] ' npm run reset-database'
```

```[tasklist]
### Tasks
```
