### ISSUE TITLE
Make a get requests for directors

### ISSUE THREAD

**Issue by Isuu1** [SchoolOfCode/bootcamp-17-bc17-w5-d4_hackathon-rest-api-postgres-hackathon_sql-postgres-node-express#3]
```[tasklist]
### Tasks
- [ ] Make a helper function
- [ ] Write a Query string to access database
- [ ] Test helper function in Postman
- [ ] Get data from helper function in app.js
- [ ] Test get request in postman
- [ ] Make a helper function for get request with specific ID
- [ ] Write a Query string to access database with specific ID
- [ ] Test helper function with ID provided
- [ ] Get data from helper function with ID in app.js
- [ ] Send back response and catch any errors
```
