### ISSUE TITLE
Make a POST request for directors

### ISSUE THREAD

**Issue by Isuu1** [SchoolOfCode/bootcamp-17-bc17-w5-d4_hackathon-rest-api-postgres-hackathon_sql-postgres-node-express#4]
```[tasklist]
### Tasks
- [ ] Write a Query string in helper function with dynamic values
- [ ] Create a new director
- [ ] Pass query string to pool database
- [ ] Get data from body request in app.js POST handler
- [ ] Send back response
- [ ] Catch any errors
```
